# Generated by Django 2.2.2 on 2020-01-01 13:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('Pharmacist', 'Pharmacist'), ('Pharmacy Technician', 'Pharmacy Technician')], max_length=10)),
                ('is_sterile_trained', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'staff',
                'verbose_name_plural': 'staff',
            },
        ),
        migrations.CreateModel(
            name='OnCallPeriod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(help_text='The date the on call period starts.', verbose_name='Start date of on call period.')),
                ('end_date', models.DateField(help_text='The date the on call period ends.', verbose_name='End date of on call period.')),
                ('tdm', models.BooleanField(blank=True, help_text='Select this if this is for a pharmacist to cover TDM only.', verbose_name='TDM pharmacist')),
                ('pharmacist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periods', to='roster.Staff')),
            ],
            options={
                'verbose_name': 'OnCall Period',
                'verbose_name_plural': 'OnCall Periods',
            },
        ),
    ]
