# Generated by Django 2.2 on 2019-05-09 06:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pharmacist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_sterile_trained', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OnCallPeriod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(help_text='The date the on call period starts.', verbose_name='Start date of on call period.')),
                ('end_date', models.DateField(help_text='The date the on call period ends.', verbose_name='End date of on call period.')),
                ('tdm', models.BooleanField(blank=True, help_text='Select this if this is for a pharmacist to cover TDM only.', verbose_name='TDM pharmacist')),
                ('pharmacist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periods', to='roster.Pharmacist')),
            ],
            options={
                'verbose_name': 'OnCall Period',
                'verbose_name_plural': 'OnCall Periods',
            },
        ),
    ]
