# Generated by Django 2.2.2 on 2020-01-01 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oncallperiod',
            name='pharmacist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='periods', to='profile.Profile'),
        ),
        migrations.DeleteModel(
            name='Staff',
        ),
    ]
