# Generated by Django 3.0.2 on 2020-01-06 08:52

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profile', '0002_auto_20200106_2150'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraShifts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='OnCallPeriod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(help_text='The date the on call period starts.', verbose_name='Start date of on call period.')),
                ('end_date', models.DateField(help_text='The date the on call period ends.', verbose_name='End date of on call period.')),
                ('tdm', models.BooleanField(blank=True, help_text='Select this if this is for a pharmacist to cover TDM only.', verbose_name='TDM pharmacist')),
                ('pharmacist', models.ForeignKey(limit_choices_to={'role': 'Pharmacist'}, on_delete=django.db.models.deletion.PROTECT, related_name='periods', to='profile.Profile')),
            ],
            options={
                'verbose_name': 'OnCall Period',
                'verbose_name_plural': 'OnCall Periods',
            },
        ),
        migrations.CreateModel(
            name='Call',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_started', models.DateTimeField(default=datetime.datetime.now)),
                ('call_type', models.CharField(choices=[('Stock', 'Stock'), ('Drug info', 'Drug info'), ('TDM', 'TDM'), ('Other', 'Other')], max_length=10)),
                ('caller_type', models.CharField(choices=[('Nurse', 'Nurse'), ('House Surgeon', 'House Surgeon'), ('Registrar', 'Registrar'), ('Consultant', 'Consultant'), ('Other', 'Other')], max_length=13)),
                ('caller_hospital', models.CharField(choices=[('Chch', 'Christchurch'), ('BWD', 'Burwood'), ('HLM', 'Hillmorton'), ('PMH', 'Princess Margaret'), ('Other', 'Other')], max_length=25)),
                ('caller_ward', models.CharField(max_length=10)),
                ('description', models.CharField(max_length=500)),
                ('call_in', models.BooleanField(default=False)),
                ('mileage', models.IntegerField(blank=True, default=0)),
                ('time_ended', models.DateTimeField()),
                ('minutes', models.IntegerField(editable=False)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calls', to='roster.OnCallPeriod')),
            ],
            options={
                'ordering': ['-time_started'],
            },
        ),
    ]
