# Generated by Django 2.2.2 on 2020-01-05 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0001_initial'),
        ('roster', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RosterPeriod',
            new_name='OnCallPeriod',
        ),
    ]
