# Generated by Django 2.2.2 on 2020-01-05 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0002_auto_20200105_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oncallperiod',
            name='pharmacist',
            field=models.ForeignKey(limit_choices_to={'role': 'Pharmacist'}, on_delete=django.db.models.deletion.PROTECT, related_name='periods', to='profile.Profile'),
        ),
    ]
