# Generated by Django 2.2 on 2019-04-25 00:52

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pharmacist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('is_sterile_trained', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Roster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='OnCall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('pharmacist', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='record.Pharmacist')),
            ],
        ),
        migrations.CreateModel(
            name='Call',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_started', models.DateTimeField(default=datetime.datetime.now)),
                ('call_type', models.CharField(choices=[('Stock', 'Stock'), ('Drug info', 'Drug info'), ('TDM', 'TDM'), ('Other', 'Other')], max_length=10)),
                ('call_in', models.BooleanField(default=False)),
                ('mileage', models.IntegerField()),
                ('time_ended', models.DateTimeField()),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='record.OnCall')),
            ],
        ),
    ]
