# Generated by Django 2.2 on 2019-05-09 06:08

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('roster', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Call',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_started', models.DateTimeField(default=datetime.datetime.now)),
                ('call_type', models.CharField(choices=[('Stock', 'Stock'), ('Drug info', 'Drug info'), ('TDM', 'TDM'), ('Other', 'Other')], max_length=10)),
                ('caller_type', models.CharField(choices=[('Nurse', 'Nurse'), ('House Surgeon', 'House Surgeon'), ('Registrar', 'Registrar'), ('Consultant', 'Consultant'), ('Other', 'Other')], max_length=13)),
                ('caller_hospital', models.CharField(choices=[('Chch', 'Christchurch'), ('BWD', 'Burwood'), ('HLM', 'Hillmorton'), ('PMH', 'Princess Margaret'), ('Other', 'Other')], max_length=25)),
                ('caller_ward', models.CharField(max_length=10)),
                ('description', models.CharField(max_length=500)),
                ('call_in', models.BooleanField(default=False)),
                ('mileage', models.IntegerField(blank=True, default=0)),
                ('time_ended', models.DateTimeField()),
                ('minutes', models.IntegerField(editable=False)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calls', to='roster.OnCallPeriod')),
            ],
            options={
                'ordering': ['-time_started'],
            },
        ),
    ]
