# Generated by Django 2.2 on 2019-04-25 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0002_auto_20190425_1255'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='oncall',
            options={'verbose_name': 'OnCall'},
        ),
        migrations.AlterField(
            model_name='call',
            name='mileage',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterUniqueTogether(
            name='oncall',
            unique_together={('pharmacist', 'start_date')},
        ),
    ]
