# Generated by Django 2.2 on 2019-04-25 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0003_auto_20190425_1308'),
    ]

    operations = [
        migrations.AddField(
            model_name='call',
            name='minutes',
            field=models.FloatField(default=1, editable=False),
            preserve_default=False,
        ),
    ]
