# Generated by Django 2.2 on 2019-04-25 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0004_call_minutes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='call',
            name='minutes',
            field=models.IntegerField(editable=False),
        ),
    ]
