# Generated by Django 2.2 on 2019-04-25 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0005_auto_20190425_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='call',
            name='description',
            field=models.CharField(default='testing', max_length=500),
            preserve_default=False,
        ),
    ]
