# Generated by Django 2.2.2 on 2020-01-01 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='user',
            new_name='username',
        ),
        migrations.AddField(
            model_name='profile',
            name='family_name',
            field=models.CharField(default='Shaw', max_length=100),
            preserve_default=False,
        ),
    ]
